name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout Suricata
      uses: actions/checkout@v2
      with:
        repository: dbcfd/suricata
        path: suricata
        ref: sensicata
    - name: Checkout libhtp
      uses: actions/checkout@v2
      with:
        repository: OISF/libhtp
        path: suricata/libhtp
    - name: Build Suricata
      working-directory: suricata
      run: autoreconf -i && ./configure --with-unix-socket && make install && make install-conf
    - name: Format
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
