name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04
    container: ubuntu:18.04

    steps:
    - uses: actions/checkout@v2
    - name: Checkout Suricata
      uses: actions/checkout@v2
      with:
        repository: dbcfd/suricata
        path: suricata
        ref: sensicata
    - name: Checkout libhtp
      uses: actions/checkout@v2
      with:
        repository: OISF/libhtp
        path: suricata/libhtp
    - name: Install Required libraries
      run: |
        apt-get update
        apt-get install -y \
          curl \
          libpcap-dev \
          libpcre3 \
          libpcre3-dev \
          libmagic-dev \
          libyaml-dev \
          libjansson-dev \
          zlib1g-dev
    - name: Install rust and tools
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        echo "::add-path::$HOME/.cargo/bin"
        rustup component add rustfmt
        cargo install --force cbindgen
    - name: Build Suricata
      working-directory: suricata
      run: autoreconf -i && ./configure --with-unix-socket && make install && make install-conf
    - name: Format
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
